### ISSUE TITLE
Stozu部署出错

### ISSUE THREAD

**Issue by dorccl4k** [fscarmen2/X-for-Stozu#1]
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./Cuberite
/entrypoint.sh: line 13: ./Cuberite: No such file or directory
Jexactyl: Server marked as offline...

**Comment by dorccl4k** [comment]
更新node.js选择后成功，感谢F佬。

**Comment by fscarmen2** [comment]
> [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... [Pterodactyl Daemon]: Finished pulling Docker container image :/home/container$ ./Cuberite /entrypoint.sh: line 13: ./Cuberite: No such file or directory Jexactyl: Server marked as offline...

我的问题，之前的图是错误的，其实我更换过新的，不知道为什么不成功。
